name = "§d§oNewb x Balance"
version = [0, 1, 0]
min_supported_mc_version = [1, 21, 111]

description = '''
§fBy Empanadas 
§3https://devendrn.github.io/newb-shader/
'''

authors = ["Empanadas","devendrn"]
url = "https://devendrn.github.io/newb-shader/"
uuid = "6252c90d-3d50-48bf-bb4c-8e8a60acf4fb"

materials = [
  "Sky", "RenderChunk", "Actor", "ActorGlint", "EndSky",
  "Clouds", "SunMoon", "Weather",
  "ItemInHandTextured", "ItemInHandColor", "ItemInHandColorGlint",
  "Stars"
]

[info]
copyright = '''
Copyright © 2025 %a, and "Newb Shader" Contributors

This compiled "Newb Shader" resource pack (source code: https://github.com/devendrn/newb-x-mcbe under MIT License) is licensed under CC BY-ND 4.0 (https://creativecommons.org/licenses/by-nd/4.0/). Redistribute only unmodified copies with proper attribution to "Newb Shader" and variant creators (if any). Do not distribute derivatives.

You can compile the shader from source and distribute the result under your own terms (compatible with the MIT License).

Contact (Discord Server): https://discord.gg/newb-community-844591537430069279
'''

credits = '''
'''

# ==============================================================================
# SUBPACKS
# ==============================================================================

[[subpack]]
define = "LOW"
materials = [
  "Sky",
  "RenderChunk",
  "Actor",
  "ActorGlint",
  "EndSky",
  "SunMoon",
  "Weather",
  "Clouds",
  "ItemInHandTextured",
  "ItemInHandColor",
  "ItemInHandColorGlint",
  "Stars"
]
description = '''
§eLow Mode - Vanilla Fancy Clouds
§7(ES) Efectos reducidos, pero visuales decentes para dispositivos débiles.  
§7(EN) Reduced effects but still decent visuals for weak devices.
'''

[[subpack]]
define = "ROUNDED_CLOUDS"
materials = [
  "Sky", 
]
description = '''
§bHigh Mode — Rounded Clouds
§7(ES) Gráficos mejorados con nubes suaves y estilizadas. Ideal si quieres calidad sin volverte loco con el realismo.  
§7(EN) Enhanced graphics with smooth, stylized clouds. Perfect if you want quality without extreme realism.
'''

[[subpack]]
define = "REALISTIC_CLOUDS"
materials = [,
  "Clouds"
]
description = '''
§bHigh Mode — Realistic Clouds
§7(ES) Gráficos mejorados con nubes realistas y detalladas. La experiencia más inmersiva del paquete.  
§7(EN) Enhanced graphics with realistic, detailed clouds. The most immersive experience.
'''